import 'dart:convert';
import 'package:flutter/services.dart';
import '../models/scheme_model.dart';

/// Loads scheme data from the bundled asset file (assets/data/schemes.json).
///
/// This keeps the app fully self-contained — no running Python server needed.
/// The JSON is generated by running:  python export_schemes.py  (in r:\DEGREE\Mad)
class SchemeApiService {
  /// Fetch all schemes from the bundled asset.
  Future<List<SchemeModel>> fetchSchemes() async {
    final raw = await rootBundle.loadString('assets/data/schemes.json');
    final List<dynamic> jsonList = json.decode(raw) as List<dynamic>;
    return jsonList
        .map((e) => SchemeModel.fromJson(e as Map<String, dynamic>))
        .where((s) => s.title.isNotEmpty)
        .toList();
  }

  /// Returns distinct category keys from the bundled data.
  Future<List<String>> fetchCategories() async {
    final schemes = await fetchSchemes();
    final seen = <String>{};
    return schemes
        .map((s) => s.category)
        .where((c) => c.isNotEmpty && seen.add(c))
        .toList();
  }
}
