// This file is generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
//
// ⚠️  You MUST replace this file with your real Firebase project values.
// Steps:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. Add an Android app with package name: com.sakshmseva.gujarat
//   3. Enable Authentication (Email/Password + Google Sign-In)
//   4. Create Firestore database
//   5. Run: flutterfire configure
//   6. Replace this file with the generated firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfKKRdVoibAWdrpI6qtO5lo0dNgzw1GI',
    appId: '1:565771310362:android:c9e185866080b11f6488a3',
    messagingSenderId: '565771310362',
    projectId: 'antigravity-app-7050e',
    storageBucket: 'antigravity-app-7050e.firebasestorage.app',
  );

  // ⚠️  REPLACE THESE VALUES with your real Firebase project config

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.sakshmseva.gujarat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGc2-Tr_OAbg3Iy7vhNJt1MK71BnWNSJs',
    appId: '1:565771310362:web:8d91c2590d124e8e6488a3',
    messagingSenderId: '565771310362',
    projectId: 'antigravity-app-7050e',
    authDomain: 'antigravity-app-7050e.firebaseapp.com',
    storageBucket: 'antigravity-app-7050e.firebasestorage.app',
    measurementId: 'G-6LH532RLM8',
  );

}